name: "Publish Python package to PyPI"

on: 
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'The tag_version, e.g. vx.x.x'
        default: 'vx.x.x'
        required: true
        type: 'string'
      python_version:
        description: 'The Python version to build with.'
        default: '3.10'
        required: true
        type: 'string'
      dry_run:
        description: 'Whether this is a dry_run publish.'
        default: 'true'
        required: true
        type: 'boolean'

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      # Checkout the repository at the specified tag version
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_version }}
      
      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      
      # Install required tools for building and publishing the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Build the package
      - name: Build the package
        run: python -m build

      # Publish to PyPI
      - name: Publish to PyPI
        run: |
          echo 'DRY_RUN: '$DRY_RUN
          if [ "$DRY_RUN" == "false" ]; then
            twine upload dist/*
          else
            twine upload --repository testpypi dist/*
          fi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          DRY_RUN: ${{ inputs.dry_run }}